package com.jenerator.controlplane.service;

import com.jenerator.common.dto.CreateJobRequest;
import com.jenerator.common.dto.JobResponse;
import com.jenerator.common.dto.UpdateJobArtifactRequest;
import com.jenerator.common.dto.UpdateJobReviewRequest;
import com.jenerator.common.dto.UpdateJobStepRequest;
import com.jenerator.common.dto.WorkerClaimResponse;
import com.jenerator.common.model.JobStatus;
import com.jenerator.common.validation.JobRules;
import com.jenerator.controlplane.domain.JobArtifactRecord;
import com.jenerator.controlplane.domain.JobRecord;
import com.jenerator.controlplane.exception.NotFoundException;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

@Service
public class JobService {
    private final ConcurrentMap<String, JobRecord> jobs = new ConcurrentHashMap<>();
    private final JobMapper mapper;

    public JobService(JobMapper mapper) {
        this.mapper = mapper;
    }

    public JobResponse create(CreateJobRequest request) {
        JobRules.requireValid(request);
        JobRecord record = JobRecord.create(request);
        record.setTitle(defaultTitle(request));
        record.setDescription("Generated by Jenerator. Review sources and rights before publishing.");
        jobs.put(record.id(), record);
        return mapper.toResponse(record);
    }

    public List<JobResponse> list() {
        return jobs.values()
                .stream()
                .sorted(Comparator.comparing(JobRecord::createdAt).reversed())
                .map(mapper::toResponse)
                .toList();
    }

    public JobResponse get(String id) {
        return mapper.toResponse(requireJob(id));
    }

    public JobResponse cancel(String id) {
        JobRecord record = requireJob(id);
        if (record.status() == JobStatus.COMPLETED || record.status() == JobStatus.FAILED) {
            throw new IllegalStateException("Finished jobs cannot be cancelled.");
        }
        record.setStatus(JobStatus.CANCELLED);
        record.updateStep("CANCELLED", "DONE", "Job cancelled.");
        return mapper.toResponse(record);
    }

    public JobResponse approveUpload(String id) {
        JobRecord record = requireJob(id);
        if (record.status() != JobStatus.WAITING_FOR_APPROVAL) {
            throw new IllegalStateException("Only jobs waiting for approval can be approved for upload.");
        }
        record.setStatus(JobStatus.APPROVED_FOR_UPLOAD);
        record.updateStep("APPROVAL", "DONE", "Upload approved from the cloud UI.");
        return mapper.toResponse(record);
    }

    public JobResponse updateReview(String id, UpdateJobReviewRequest request) {
        JobRecord record = requireJob(id);
        if (record.status() == JobStatus.APPROVED_FOR_UPLOAD
                || record.status() == JobStatus.UPLOADING
                || record.status() == JobStatus.COMPLETED
                || record.status() == JobStatus.CANCELLED) {
            throw new IllegalStateException("Jobs cannot be edited after upload approval, completion, or cancellation.");
        }
        record.updateReview(
                request.title(),
                request.description(),
                request.tags(),
                request.citations(),
                request.madeForKids(),
                request.containsSyntheticMedia()
        );
        record.updateStep("REVIEW", "DONE", "Review metadata updated.");
        return mapper.toResponse(record);
    }

    public WorkerClaimResponse claim(String workerId) {
        return jobs.values()
                .stream()
                .filter(job -> job.status() == JobStatus.QUEUED || job.status() == JobStatus.APPROVED_FOR_UPLOAD)
                .sorted(Comparator.comparing(JobRecord::createdAt))
                .findFirst()
                .map(job -> claim(job, workerId))
                .orElseGet(WorkerClaimResponse::empty);
    }

    public void updateStep(String jobId, UpdateJobStepRequest request) {
        JobRecord record = requireJob(jobId);
        if (request.jobStatus() != null) {
            record.setStatus(request.jobStatus());
        }
        record.updateStep(request.stepName(), request.stepStatus(), request.message());
    }

    public void addArtifact(String jobId, UpdateJobArtifactRequest request) {
        JobRecord record = requireJob(jobId);
        addArtifactRecord(record, new JobArtifactRecord(
                UUID.randomUUID().toString(),
                request.type(),
                request.filename(),
                request.url(),
                request.sizeBytes(),
                Instant.now()
        ));
    }

    public void addArtifactRecord(String jobId, JobArtifactRecord artifact) {
        addArtifactRecord(requireJob(jobId), artifact);
    }

    private void addArtifactRecord(JobRecord record, JobArtifactRecord artifact) {
        record.addArtifact(artifact);
    }

    private WorkerClaimResponse claim(JobRecord job, String workerId) {
        synchronized (job) {
            if (job.status() == JobStatus.QUEUED) {
                job.claimFor(workerId, JobStatus.CLAIMED);
                job.updateStep("CLAIMED", "DONE", "Local worker claimed the render job.");
                return new WorkerClaimResponse(true, mapper.toResponse(job));
            }
            if (job.status() == JobStatus.APPROVED_FOR_UPLOAD) {
                job.claimFor(workerId, JobStatus.UPLOADING);
                job.updateStep("UPLOAD", "RUNNING", "Local worker claimed the approved upload.");
                return new WorkerClaimResponse(true, mapper.toResponse(job));
            }
            return WorkerClaimResponse.empty();
        }
    }

    private JobRecord requireJob(String id) {
        JobRecord record = jobs.get(id);
        if (record == null) {
            throw new NotFoundException("Job not found: " + id);
        }
        return record;
    }

    private String defaultTitle(CreateJobRequest request) {
        String normalized = request.prompt().replaceAll("\\s+", " ").trim();
        String clipped = normalized.length() > 70 ? normalized.substring(0, 67) + "..." : normalized;
        return switch (request.videoType()) {
            case SUMMARY -> "Summary: " + clipped;
            case RECAP -> "Recap: " + clipped;
            case TOP_LIST -> "Top List: " + clipped;
            case RECOMMENDATION -> "Watch Next: " + clipped;
        };
    }
}
