package com.jenerator.controlplane.service;

import com.jenerator.common.dto.CreateJobRequest;
import com.jenerator.common.dto.JobResponse;
import com.jenerator.common.dto.UpdateJobArtifactRequest;
import com.jenerator.common.dto.UpdateJobReviewRequest;
import com.jenerator.common.dto.UpdateJobStepRequest;
import com.jenerator.common.dto.WorkerClaimResponse;
import com.jenerator.common.model.JobStatus;
import com.jenerator.common.validation.JobRules;
import com.jenerator.controlplane.domain.JobArtifactRecord;
import com.jenerator.controlplane.domain.JobRecord;
import com.jenerator.controlplane.domain.JobSnapshot;
import com.jenerator.controlplane.exception.NotFoundException;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

@Service
public class JobService {
    private final ConcurrentMap<String, JobRecord> jobs = new ConcurrentHashMap<>();
    private final JobMapper mapper;
    private final ControlPlaneStateStore stateStore;

    public JobService(JobMapper mapper, ControlPlaneStateStore stateStore) {
        this.mapper = mapper;
        this.stateStore = stateStore;
        loadPersistedJobs();
    }

    JobService(JobMapper mapper) {
        this.mapper = mapper;
        this.stateStore = null;
    }

    public JobResponse create(CreateJobRequest request) {
        JobRules.requireValid(request);
        JobRecord record = JobRecord.create(request);
        record.setTitle(defaultTitle(request));
        record.setDescription("Generated by Jenerator. Review sources and rights before publishing.");
        jobs.put(record.id(), record);
        persist();
        return mapper.toResponse(record);
    }

    public List<JobResponse> list() {
        return jobs.values()
                .stream()
                .sorted(Comparator.comparing(JobRecord::createdAt).reversed())
                .map(mapper::toResponse)
                .toList();
    }

    public JobResponse get(String id) {
        return mapper.toResponse(requireJob(id));
    }

    public JobResponse cancel(String id) {
        JobRecord record = requireJob(id);
        if (record.status() == JobStatus.COMPLETED || record.status() == JobStatus.FAILED) {
            throw new IllegalStateException("Finished jobs cannot be cancelled.");
        }
        record.setStatus(JobStatus.CANCELLED);
        record.updateStep("CANCELLED", "DONE", "Job cancelled.");
        persist();
        return mapper.toResponse(record);
    }

    public JobResponse approveUpload(String id) {
        JobRecord record = requireJob(id);
        if (record.status() != JobStatus.WAITING_FOR_APPROVAL) {
            throw new IllegalStateException("Only jobs waiting for approval can be approved for upload.");
        }
        List<String> readinessErrors = uploadReadinessErrors(record);
        if (!readinessErrors.isEmpty()) {
            throw new IllegalStateException("Job is not ready for upload approval: " + String.join(" ", readinessErrors));
        }
        record.setStatus(JobStatus.APPROVED_FOR_UPLOAD);
        record.updateStep("APPROVAL", "DONE", "Upload approved from the cloud UI.");
        persist();
        return mapper.toResponse(record);
    }

    public JobResponse updateReview(String id, UpdateJobReviewRequest request) {
        JobRecord record = requireJob(id);
        if (record.status() == JobStatus.APPROVED_FOR_UPLOAD
                || record.status() == JobStatus.UPLOADING
                || record.status() == JobStatus.COMPLETED
                || record.status() == JobStatus.CANCELLED) {
            throw new IllegalStateException("Jobs cannot be edited after upload approval, completion, or cancellation.");
        }
        record.updateReview(
                trimToEmpty(request.title()),
                trimToEmpty(request.description()),
                cleanedList(request.tags()),
                cleanedList(request.citations()),
                request.madeForKids(),
                request.containsSyntheticMedia()
        );
        record.updateStep("REVIEW", "DONE", "Review metadata updated.");
        persist();
        return mapper.toResponse(record);
    }

    public WorkerClaimResponse claim(String workerId) {
        return claim(workerId, true, true);
    }

    public WorkerClaimResponse claim(String workerId, boolean canRender, boolean canUpload) {
        return jobs.values()
                .stream()
                .filter(job -> job.status() == JobStatus.QUEUED || job.status() == JobStatus.APPROVED_FOR_UPLOAD)
                .filter(job -> canClaim(job, canRender, canUpload))
                .sorted(Comparator.comparing(JobRecord::createdAt))
                .findFirst()
                .map(job -> claim(job, workerId))
                .orElseGet(WorkerClaimResponse::empty);
    }

    public void updateStep(String jobId, UpdateJobStepRequest request) {
        JobRecord record = requireJob(jobId);
        if (record.status() == JobStatus.CANCELLED) {
            return;
        }
        if (request.jobStatus() != null) {
            record.setStatus(request.jobStatus());
        }
        record.updateStep(request.stepName(), request.stepStatus(), request.message());
        persist();
    }

    public void addArtifact(String jobId, UpdateJobArtifactRequest request) {
        JobRecord record = requireJob(jobId);
        addArtifactRecord(record, new JobArtifactRecord(
                UUID.randomUUID().toString(),
                request.type(),
                request.filename(),
                request.url(),
                request.sizeBytes(),
                Instant.now()
        ));
    }

    public void addArtifactRecord(String jobId, JobArtifactRecord artifact) {
        addArtifactRecord(requireJob(jobId), artifact);
    }

    private void addArtifactRecord(JobRecord record, JobArtifactRecord artifact) {
        record.addArtifact(artifact);
        persist();
    }

    private List<String> uploadReadinessErrors(JobRecord record) {
        List<String> errors = new ArrayList<>();
        if (!hasArtifact(record, "PREVIEW_VIDEO")) {
            errors.add("Review a rendered preview video first.");
        }
        if (!hasText(record.title())) {
            errors.add("Title is required.");
        }
        if (!hasText(record.description())) {
            errors.add("Description is required.");
        }
        if (record.tags().isEmpty()) {
            errors.add("At least one tag is required.");
        }
        if (record.citations().isEmpty()) {
            errors.add("At least one citation is required.");
        }
        return errors;
    }

    private boolean hasArtifact(JobRecord record, String type) {
        return record.artifacts()
                .stream()
                .anyMatch(artifact -> type.equals(artifact.type()));
    }

    private boolean canClaim(JobRecord job, boolean canRender, boolean canUpload) {
        if (job.status() == JobStatus.QUEUED) {
            return canRender;
        }
        if (job.status() == JobStatus.APPROVED_FOR_UPLOAD) {
            return canUpload;
        }
        return false;
    }

    private WorkerClaimResponse claim(JobRecord job, String workerId) {
        synchronized (job) {
            if (job.status() == JobStatus.QUEUED) {
                job.claimFor(workerId, JobStatus.CLAIMED);
                job.updateStep("CLAIMED", "DONE", "Local worker claimed the render job.");
                persist();
                return new WorkerClaimResponse(true, mapper.toResponse(job));
            }
            if (job.status() == JobStatus.APPROVED_FOR_UPLOAD) {
                job.claimFor(workerId, JobStatus.UPLOADING);
                job.updateStep("UPLOAD", "RUNNING", "Local worker claimed the approved upload.");
                persist();
                return new WorkerClaimResponse(true, mapper.toResponse(job));
            }
            return WorkerClaimResponse.empty();
        }
    }

    private JobRecord requireJob(String id) {
        JobRecord record = jobs.get(id);
        if (record == null) {
            throw new NotFoundException("Job not found: " + id);
        }
        return record;
    }

    private String defaultTitle(CreateJobRequest request) {
        String normalized = request.prompt().replaceAll("\\s+", " ").trim();
        String clipped = normalized.length() > 70 ? normalized.substring(0, 67) + "..." : normalized;
        return switch (request.videoType()) {
            case SUMMARY -> "Summary: " + clipped;
            case RECAP -> "Recap: " + clipped;
            case TOP_LIST -> "Top List: " + clipped;
            case RECOMMENDATION -> "Watch Next: " + clipped;
        };
    }

    private List<String> cleanedList(List<String> values) {
        if (values == null) {
            return List.of();
        }
        return values.stream()
                .map(this::trimToEmpty)
                .filter(this::hasText)
                .distinct()
                .toList();
    }

    private String trimToEmpty(String value) {
        return value == null ? "" : value.trim();
    }

    private boolean hasText(String value) {
        return value != null && !value.isBlank();
    }

    private void loadPersistedJobs() {
        List<JobSnapshot> snapshots = stateStore.readJobs();
        for (JobSnapshot snapshot : snapshots) {
            JobRecord record = JobRecord.restore(snapshot);
            recoverTransientState(record);
            jobs.put(record.id(), record);
        }
        if (!snapshots.isEmpty()) {
            persist();
        }
    }

    private void recoverTransientState(JobRecord record) {
        if (record.status() == JobStatus.CLAIMED || record.status() == JobStatus.RUNNING) {
            record.setStatus(JobStatus.QUEUED);
            record.updateStep("RECOVERED", "DONE", "Control plane restarted; render job returned to queue.");
        }
        if (record.status() == JobStatus.UPLOADING) {
            record.setStatus(JobStatus.APPROVED_FOR_UPLOAD);
            record.updateStep("RECOVERED", "DONE", "Control plane restarted; upload job returned to approval queue.");
        }
    }

    private void persist() {
        if (stateStore == null) {
            return;
        }
        stateStore.writeJobs(jobs.values()
                .stream()
                .map(JobRecord::snapshot)
                .toList());
    }
}
